# Generated by Django 3.2.8 on 2021-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='descrição')),
                ('campo_1', models.CharField(max_length=10)),
                ('campo_2', models.CharField(blank=True, max_length=10)),
                ('campo_3', models.CharField(max_length=10, null=True)),
                ('campo_4', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
