# Generated by Django 3.2.8 on 2021-10-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='campo_1',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='campo_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='campo_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='campo_4',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
